name: Check pull request
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verstion: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm i
      - name: Check lint
        run: npm run lint
      - name: Run tests
        run: npm run test
